# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: [6.0.x]

    env:
      SOLUTION_FILE_PATH: ./src/Hpl2Parser.sln

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --no-restore

  test:

    needs: build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: [6.0.x]

    env:
      TEST_PROJECT_PATH: ./src/Hpl2Parser.Tests/Hpl2Parser.Tests.csproj

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.TEST_PROJECT_PATH }}
    - name: Test with Coverage
      run: |
        dotnet tool install --global coverlet.console
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        coverlet ${{ env.TEST_PROJECT_PATH }} --target "dotnet" --targetargs "test ${{ env.TEST_PROJECT_PATH }} --no-build --verbosity normal" --format cobertura --output './coverage/'
    - name: Create Coverage Report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        reportgenerator -reports:./coverage/coverage.cobertura.xml -targetdir:./coverage/reports/ -reporttypes:Html
    - name: Publish Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./coverage/reports/
